name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {} # disable all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for peaceiris/actions-gh-pages

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci
      - run: npm run build:production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
