name: Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions: { }

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
          cache-dependency-path: package-lock.json

      - name: NPM install
        run: npm ci

      - name: Vitest
        run: npm test
